import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // 1. Clean existing records
  await prisma.user.deleteMany({});
  await prisma.ghat.deleteMany({});
  await prisma.monitoringData.deleteMany({});
  await prisma.district.deleteMany({});
  await prisma.alert.deleteMany({});
  await prisma.cameraFeed.deleteMany({});
  await prisma.report.deleteMany({});
  await prisma.shiftOfficer.deleteMany({});

  // 2. Hash default passwords
  const adminPasswordHash = bcrypt.hashSync('Admin@123', 10);
  const supervisorPasswordHash = bcrypt.hashSync('Super@123', 10);

  // 3. Create Users
  await prisma.user.createMany({
    data: [
      {
        username: 'admin',
        password: adminPasswordHash,
        passcode: 'Admin@123',
        role: 'admin',
        fullName: 'Command Center Admin',
        employeeId: 'ICCC-ADMIN-01',
        mobileNumber: '+91 99999 99999',
        email: 'admin@iccc.ap.gov.in',
        assignedDistrict: 'All Districts',
        shiftTiming: 'Full Time',
        status: 'active',
      },
      {
        username: 'supervisor',
        password: supervisorPasswordHash,
        passcode: 'Super@123',
        role: 'command-supervisor',
        fullName: 'Officer Rajesh Kumar',
        employeeId: 'SUP-2026-009',
        mobileNumber: '+91 98480 22334',
        email: 'rajesh.kumar@iccc.ap.gov.in',
        assignedDistrict: 'East Godavari',
        shiftTiming: 'Morning Shift (06:00 - 14:00)',
        status: 'active',
        lastLogin: '2026-05-24T06:01:22.000Z',
      },
      {
        username: 'supervisor2',
        password: supervisorPasswordHash,
        passcode: 'Super@123',
        role: 'command-supervisor',
        fullName: 'Officer Anjali Naidu',
        employeeId: 'SUP-2026-015',
        mobileNumber: '+91 81223 99881',
        email: 'anjali.n@iccc.ap.gov.in',
        assignedDistrict: 'West Godavari',
        shiftTiming: 'Afternoon Shift (14:00 - 22:00)',
        status: 'active',
        lastLogin: '2026-05-23T14:15:30.000Z',
      },
      {
        username: 'supervisor3',
        password: supervisorPasswordHash,
        passcode: 'Super@123',
        role: 'command-supervisor',
        fullName: 'Officer Srinivas Rao',
        employeeId: 'SUP-2026-033',
        mobileNumber: '+91 99008 77665',
        email: 'srinivas.r@iccc.ap.gov.in',
        assignedDistrict: 'Khammam',
        shiftTiming: 'Night Shift (22:00 - 06:00)',
        status: 'inactive',
        lastLogin: 'Never',
      },
    ],
  });

  // 4. Create Districts
  await prisma.district.createMany({
    data: [
      { name: 'East Godavari' },
      { name: 'West Godavari' },
      { name: 'Khammam' },
    ],
  });

  // 5. Create 12 Ghats
  await prisma.ghat.createMany({
    data: [
      // East Godavari
      {
        id: 'ghat-dowleswaram',
        ghatName: 'Dowleswaram Ghat',
        district: 'East Godavari',
        capacity: 8000,
        currentCrowd: 4500,
        occupancyPercentage: 56.2,
        entryCount: 5000,
        exitCount: 500,
        activeCameras: 24,
        zoneStatus: 'CROWDED',
        aiRisk: 'busy',
        latitude: 16.940,
        longitude: 81.782,
        coordinatesX: 42.0,
        coordinatesY: 20.0,
        anomaliesDetected: 1,
        safetyStatus: 'Verbal warning broadcasts active',
        inMen: 2500,
        inWomen: 2300,
        inOthers: 200,
        outMen: 300,
        outWomen: 150,
        outOthers: 50,
        camInId: 'CAM-IN-DOWL-01',
        camOutId: 'CAM-OUT-DOWL-01',
        aiTrend: 'Peak projected in 15m',
        lastUpdated: 'Just Now',
      },
      {
        id: 'ghat-goshpada',
        ghatName: 'Goshpada Ghat',
        district: 'East Godavari',
        capacity: 6500,
        currentCrowd: 2800,
        occupancyPercentage: 43.1,
        entryCount: 3200,
        exitCount: 400,
        activeCameras: 18,
        zoneStatus: 'CROWDED',
        aiRisk: 'moderate',
        latitude: 17.005,
        longitude: 81.721,
        coordinatesX: 48.0,
        coordinatesY: 28.0,
        anomaliesDetected: 0,
        safetyStatus: 'Nominal flow bounds',
        inMen: 1500,
        inWomen: 1600,
        inOthers: 100,
        outMen: 200,
        outWomen: 150,
        outOthers: 50,
        camInId: 'CAM-IN-GOSH-01',
        camOutId: 'CAM-OUT-GOSH-01',
        aiTrend: 'Flow velocity normal',
        lastUpdated: 'Just Now',
      },
      {
        id: 'ghat-kotipalli',
        ghatName: 'Kotipalli Ghat',
        district: 'East Godavari',
        capacity: 5000,
        currentCrowd: 1200,
        occupancyPercentage: 24.0,
        entryCount: 1550,
        exitCount: 350,
        activeCameras: 12,
        zoneStatus: 'OPEN ZONE',
        aiRisk: 'safe',
        latitude: 16.698,
        longitude: 82.046,
        coordinatesX: 55.0,
        coordinatesY: 35.0,
        anomaliesDetected: 0,
        safetyStatus: 'Safe clearance capacity margins',
        inMen: 800,
        inWomen: 700,
        inOthers: 50,
        outMen: 200,
        outWomen: 100,
        outOthers: 50,
        camInId: 'CAM-IN-KOTI-01',
        camOutId: 'CAM-OUT-KOTI-01',
        aiTrend: 'Low density clearance',
        lastUpdated: '3 mins ago',
      },
      {
        id: 'ghat-pushkar',
        ghatName: 'Pushkar Ghat',
        district: 'East Godavari',
        capacity: 9000,
        currentCrowd: 7200,
        occupancyPercentage: 80.0,
        entryCount: 8500,
        exitCount: 1300,
        activeCameras: 36,
        zoneStatus: 'HIGHLY CROWDED',
        aiRisk: 'busy',
        latitude: 17.000,
        longitude: 81.776,
        coordinatesX: 50.0,
        coordinatesY: 12.0,
        anomaliesDetected: 2,
        safetyStatus: 'Entry gating controls recommended',
        inMen: 4200,
        inWomen: 4000,
        inOthers: 300,
        outMen: 800,
        outWomen: 400,
        outOthers: 100,
        camInId: 'CAM-IN-PUSH-01',
        camOutId: 'CAM-OUT-PUSH-01',
        aiTrend: 'Steady flow projected',
        lastUpdated: 'Just Now',
      },
      // West Godavari
      {
        id: 'ghat-kovvur',
        ghatName: 'Kovvur Ghat',
        district: 'West Godavari',
        capacity: 7500,
        currentCrowd: 4800,
        occupancyPercentage: 64.0,
        entryCount: 5550,
        exitCount: 750,
        activeCameras: 22,
        zoneStatus: 'CROWDED',
        aiRisk: 'busy',
        latitude: 17.018,
        longitude: 81.728,
        coordinatesX: 62.0,
        coordinatesY: 48.0,
        anomaliesDetected: 0,
        safetyStatus: 'Monitoring inflow streams',
        inMen: 2800,
        inWomen: 2600,
        inOthers: 150,
        outMen: 400,
        outWomen: 300,
        outOthers: 50,
        camInId: 'CAM-IN-KOVV-01',
        camOutId: 'CAM-OUT-KOVV-01',
        aiTrend: 'Devotee inflow rising',
        lastUpdated: 'Just Now',
      },
      {
        id: 'ghat-narasapuram',
        ghatName: 'Narasapuram Ghat',
        district: 'West Godavari',
        capacity: 6000,
        currentCrowd: 1500,
        occupancyPercentage: 25.0,
        entryCount: 1950,
        exitCount: 450,
        activeCameras: 14,
        zoneStatus: 'OPEN ZONE',
        aiRisk: 'safe',
        latitude: 16.438,
        longitude: 81.700,
        coordinatesX: 68.0,
        coordinatesY: 56.0,
        anomaliesDetected: 0,
        safetyStatus: 'Monitoring normal flow levels',
        inMen: 1000,
        inWomen: 900,
        inOthers: 50,
        outMen: 250,
        outWomen: 150,
        outOthers: 50,
        camInId: 'CAM-IN-NARA-01',
        camOutId: 'CAM-OUT-NARA-01',
        aiTrend: 'Monitoring stable',
        lastUpdated: 'Just Now',
      },
      {
        id: 'ghat-pattiseema',
        ghatName: 'Pattiseema Ghat',
        district: 'West Godavari',
        capacity: 7000,
        currentCrowd: 5400,
        occupancyPercentage: 77.1,
        entryCount: 6300,
        exitCount: 900,
        activeCameras: 28,
        zoneStatus: 'HIGHLY CROWDED',
        aiRisk: 'busy',
        latitude: 17.155,
        longitude: 81.605,
        coordinatesX: 78.0,
        coordinatesY: 72.0,
        anomaliesDetected: 1,
        safetyStatus: 'Diversion routing active',
        inMen: 3200,
        inWomen: 3000,
        inOthers: 100,
        outMen: 500,
        outWomen: 350,
        outOthers: 50,
        camInId: 'CAM-IN-PATT-01',
        camOutId: 'CAM-OUT-PATT-01',
        aiTrend: 'Flow vector stable',
        lastUpdated: '3 mins ago',
      },
      {
        id: 'ghat-siddhantam',
        ghatName: 'Siddhantam Ghat',
        district: 'West Godavari',
        capacity: 5500,
        currentCrowd: 1100,
        occupancyPercentage: 20.0,
        entryCount: 1350,
        exitCount: 250,
        activeCameras: 10,
        zoneStatus: 'OPEN ZONE',
        aiRisk: 'safe',
        latitude: 16.732,
        longitude: 81.784,
        coordinatesX: 72.0,
        coordinatesY: 64.0,
        anomaliesDetected: 0,
        safetyStatus: 'Clear access gates',
        inMen: 700,
        inWomen: 600,
        inOthers: 50,
        outMen: 150,
        outWomen: 80,
        outOthers: 20,
        camInId: 'CAM-IN-SIDD-01',
        camOutId: 'CAM-OUT-SIDD-01',
        aiTrend: 'Standard flow index',
        lastUpdated: 'Just Now',
      },
      // Khammam
      {
        id: 'ghat-bhadrachalam',
        ghatName: 'Bhadrachalam Main Ghat',
        district: 'Khammam',
        capacity: 7500,
        currentCrowd: 5920,
        occupancyPercentage: 78.9,
        entryCount: 6850,
        exitCount: 930,
        activeCameras: 34,
        zoneStatus: 'HIGHLY CROWDED',
        aiRisk: 'busy',
        latitude: 17.670,
        longitude: 80.887,
        coordinatesX: 78.0,
        coordinatesY: 30.0,
        anomaliesDetected: 1,
        safetyStatus: 'Crowd routing advisory active',
        inMen: 3500,
        inWomen: 3200,
        inOthers: 150,
        outMen: 500,
        outWomen: 350,
        outOthers: 80,
        camInId: 'CAM-IN-BHAD-01',
        camOutId: 'CAM-OUT-BHAD-01',
        aiTrend: 'Bathing steps density elevated',
        lastUpdated: '2 mins ago',
      },
      {
        id: 'ghat-edugurallapalli',
        ghatName: 'Edugurallapalli Ghat',
        district: 'Khammam',
        capacity: 5000,
        currentCrowd: 950,
        occupancyPercentage: 19.0,
        entryCount: 1180,
        exitCount: 230,
        activeCameras: 8,
        zoneStatus: 'OPEN ZONE',
        aiRisk: 'safe',
        latitude: 17.755,
        longitude: 80.932,
        coordinatesX: 82.0,
        coordinatesY: 22.0,
        anomaliesDetected: 0,
        safetyStatus: 'Nominal operation parameters',
        inMen: 600,
        inWomen: 550,
        inOthers: 30,
        outMen: 120,
        outWomen: 80,
        outOthers: 30,
        camInId: 'CAM-IN-EDUG-01',
        camOutId: 'CAM-OUT-EDUG-01',
        aiTrend: 'Safe flow margins',
        lastUpdated: 'Just Now',
      },
      {
        id: 'ghat-koonavaram',
        ghatName: 'Koonavaram Ghat',
        district: 'Khammam',
        capacity: 6000,
        currentCrowd: 2100,
        occupancyPercentage: 35.0,
        entryCount: 2400,
        exitCount: 300,
        activeCameras: 16,
        zoneStatus: 'CROWDED',
        aiRisk: 'moderate',
        latitude: 17.585,
        longitude: 81.258,
        coordinatesX: 86.0,
        coordinatesY: 38.0,
        anomaliesDetected: 0,
        safetyStatus: 'Monitoring confluence flow status',
        inMen: 1200,
        inWomen: 1100,
        inOthers: 100,
        outMen: 180,
        outWomen: 100,
        outOthers: 20,
        camInId: 'CAM-IN-KOON-01',
        camOutId: 'CAM-OUT-KOON-01',
        aiTrend: 'Steady volume index',
        lastUpdated: '5 mins ago',
      },
      {
        id: 'ghat-seetharama',
        ghatName: 'Seetharama Ghat',
        district: 'Khammam',
        capacity: 7000,
        currentCrowd: 5100,
        occupancyPercentage: 72.9,
        entryCount: 5900,
        exitCount: 800,
        activeCameras: 24,
        zoneStatus: 'CROWDED',
        aiRisk: 'busy',
        latitude: 17.662,
        longitude: 80.895,
        coordinatesX: 90.0,
        coordinatesY: 45.0,
        anomaliesDetected: 1,
        safetyStatus: 'Advisory routing active',
        inMen: 3000,
        inWomen: 2800,
        inOthers: 100,
        outMen: 400,
        outWomen: 350,
        outOthers: 50,
        camInId: 'CAM-IN-SEET-01',
        camOutId: 'CAM-OUT-SEET-01',
        aiTrend: 'Advisory routing active',
        lastUpdated: 'Just Now',
      },
    ],
  });

  // 6. Create CCTV Feeds
  await prisma.cameraFeed.createMany({
    data: [
      {
        id: 'CAM-IN-DOWL-01',
        location: 'Dowleswaram - Barrage Entrance Plaza',
        resolution: '4K UHD @ 30FPS',
        peopleCount: 254,
        densityLabel: 'Elevated',
        aiDetections: ['Pedestrian queuing active', 'Plaza cluster'],
        riskLevel: 'busy',
        feedStatus: 'online',
        boundingBoxes: [
          { x: 30, y: 50, w: 140, h: 160, label: 'Queue overload 74%' },
        ],
      },
      {
        id: 'CAM-IN-BHAD-01',
        location: 'Bhadrachalam Main - Bathing Stairs',
        resolution: '1080p HD @ 60FPS',
        peopleCount: 385,
        densityLabel: 'High Density',
        aiDetections: ['Bathing stairs congestion threshold hit'],
        riskLevel: 'busy',
        feedStatus: 'online',
        boundingBoxes: [
          { x: 80, y: 60, w: 220, h: 130, label: 'Stair cluster 82%' },
        ],
      },
      {
        id: 'CAM-IN-PUSH-01',
        location: 'Pushkar Ghat - Entrance Gateway',
        resolution: '4K UHD @ 30FPS',
        peopleCount: 198,
        densityLabel: 'Elevated',
        aiDetections: ['Devotee flow constant'],
        riskLevel: 'busy',
        feedStatus: 'online',
        boundingBoxes: [],
      },
      {
        id: 'CAM-IN-KOVV-01',
        location: 'Kovvur Ghat - Access Platform',
        resolution: '1080p HD @ 60FPS',
        peopleCount: 142,
        densityLabel: 'Moderate',
        aiDetections: ['Nominal platform pacing'],
        riskLevel: 'moderate',
        feedStatus: 'online',
        boundingBoxes: [],
      },
    ],
  });

  // 7. Create Incident Logs (Alerts)
  await prisma.alert.createMany({
    data: [
      {
        id: 'INC-2026-981',
        time: '15:52:14',
        location: 'Pushkar Ghat',
        category: 'Crowd Bottleneck',
        severity: 'warning',
        description: 'AI vision detected gate approach capacity nearing 80%. Entry rate modulation active.',
        status: 'dispatched',
        assignedUnit: 'Rapid Response Team Alpha',
      },
      {
        id: 'INC-2026-980',
        time: '15:48:30',
        location: 'Bhadrachalam Main Ghat',
        category: 'Flow Stagnation',
        severity: 'warning',
        description: 'Devotee pedestrian velocity dropped below 0.3m/s on lower bathing steps. PA advisory issued.',
        status: 'pending',
        assignedUnit: 'Station Command Speaker System',
      },
      {
        id: 'INC-2026-979',
        time: '15:15:00',
        location: 'Dowleswaram Ghat',
        category: 'Entry Overflow',
        severity: 'moderate',
        description: 'Minor queue spillover at gate 2. Resolved via auxiliary platform routing.',
        status: 'resolved',
        assignedUnit: 'Patrol Team 4',
      },
      {
        id: 'INC-2026-978',
        time: '14:42:10',
        location: 'Kotipalli Ghat',
        category: 'Routine Check',
        severity: 'moderate',
        description: 'Standard density check complete. All bathing and plaza areas operating safely.',
        status: 'resolved',
        assignedUnit: 'Local Command Guard',
      },
    ],
  });

  // 8. Create Shift Officers
  await prisma.shiftOfficer.createMany({
    data: [
      {
        officerName: 'Officer Rajesh Kumar',
        officerId: 'SUP-2026-009',
        district: 'East Godavari',
        assignedGhat: 'Dowleswaram Ghat',
        shiftTime: 'Morning Shift (06:00 AM - 02:00 PM)',
        contactNumber: '+91 98480 22334',
        dutyStatus: 'active',
        attendance: 'Present',
        reportingOfficer: 'Collector East Godavari',
        emergencyContact: '+91 98480 11223',
      },
      {
        officerName: 'Officer Anjali Naidu',
        officerId: 'SUP-2026-015',
        district: 'West Godavari',
        assignedGhat: 'Kovvur Ghat',
        shiftTime: 'Afternoon Shift (02:00 PM - 10:00 PM)',
        contactNumber: '+91 81223 99881',
        dutyStatus: 'break',
        attendance: 'Present',
        reportingOfficer: 'Collector West Godavari',
        emergencyContact: '+91 81223 88776',
      },
      {
        officerName: 'Officer Srinivas Rao',
        officerId: 'SUP-2026-033',
        district: 'Khammam',
        assignedGhat: 'Bhadrachalam Main Ghat',
        shiftTime: 'Night Shift (10:00 PM - 06:00 AM)',
        contactNumber: '+91 99008 77665',
        dutyStatus: 'offline',
        attendance: 'Absent',
        reportingOfficer: 'SP Khammam Police',
        emergencyContact: '+91 99008 66554',
      },
      {
        officerName: 'Inspector M. Venkatesh',
        officerId: 'ERT-2026-102',
        district: 'East Godavari',
        assignedGhat: 'Pushkar Ghat',
        shiftTime: 'Emergency Response Shift (08:00 AM - 08:00 PM)',
        contactNumber: '+91 94405 55432',
        dutyStatus: 'active',
        attendance: 'Present',
        reportingOfficer: 'DIG Godavari Range',
        emergencyContact: '+91 94405 44321',
      },
      {
        officerName: 'Officer K. Rama Devi',
        officerId: 'SUP-2026-042',
        district: 'West Godavari',
        assignedGhat: 'Pattiseema Ghat',
        shiftTime: 'Morning Shift (06:00 AM - 02:00 PM)',
        contactNumber: '+91 73820 11229',
        dutyStatus: 'active',
        attendance: 'Present',
        reportingOfficer: 'Sub-Collector Kovvur',
        emergencyContact: '+91 73820 22330',
      },
      {
        officerName: 'Officer Ch. Sai Kiran',
        officerId: 'SUP-2026-056',
        district: 'Khammam',
        assignedGhat: 'Koonavaram Ghat',
        shiftTime: 'Afternoon Shift (02:00 PM - 10:00 PM)',
        contactNumber: '+91 88970 44332',
        dutyStatus: 'offline',
        attendance: 'Present',
        reportingOfficer: 'RDO Bhadrachalam',
        emergencyContact: '+91 88970 33221',
      },
      {
        officerName: 'Officer T. Prasanna',
        officerId: 'SUP-2026-078',
        district: 'East Godavari',
        assignedGhat: 'Kotipalli Ghat',
        shiftTime: 'Afternoon Shift (02:00 PM - 10:00 PM)',
        contactNumber: '+91 91772 88991',
        dutyStatus: 'break',
        attendance: 'Present',
        reportingOfficer: 'Collector East Godavari',
        emergencyContact: '+91 91772 77880',
      },
      {
        officerName: 'Commander B. Ravi',
        officerId: 'ERT-2026-118',
        district: 'West Godavari',
        assignedGhat: 'Narasapuram Ghat',
        shiftTime: 'Emergency Response Shift (08:00 AM - 08:00 PM)',
        contactNumber: '+91 95503 66110',
        dutyStatus: 'active',
        attendance: 'Present',
        reportingOfficer: 'Commandant SDRF AP',
        emergencyContact: '+91 95503 55009',
      },
    ],
  });

  // 9. Create MonitoringData
  await prisma.monitoringData.create({
    data: {
      temp: '34°C',
      condition: 'Partly Cloudy',
      humidity: '68%',
      wind: '12 km/h SE',
      waterLevel: 'Safe (+0.38m)',
      safetyAlert: 'No severe weather alerts active for Godavari corridor.',
      totalMonitoredGhats: 12,
      activeFeeds: 24,
      onlineSensors: 112,
      incidentsResolvedToday: 18,
      citizenReportsReceived: 96,
      aiModelAccuracy: '97.4%',
      inferenceLatency: '38ms',
    },
  });

  console.log('Database successfully seeded!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
